import type { Metadata } from "next";
import "./globals.css";
import {kanit} from './fonts'

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <h1>Todo List</h1>
        {children}
      </body>
    </html>
  );
}
